const ORDER_STATUS = {
  PENDING: 'PENDING',
  PICKUP: 'PICKUP',
  WASHING: 'WASHING',
  DRYING: 'DRYING',
  IRONING: 'IRONING',
  PACKING: 'PACKING',
  READY: 'READY',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const ORDER_STATUS_LABEL = {
  PENDING: 'Menunggu',
  PICKUP: 'Penjemputan',
  WASHING: 'Dicuci',
  DRYING: 'Dikeringkan',
  IRONING: 'Disetrika',
  PACKING: 'Dikemas',
  READY: 'Siap Diambil',
  DELIVERED: 'Di antar',
  COMPLETED: 'Selesai',
  CANCELLED: 'Dibatalkan',
};

const ORDER_TRANSITIONS = {
  [ORDER_STATUS.PENDING]: [ORDER_STATUS.PICKUP, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PICKUP]: [ORDER_STATUS.WASHING, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.WASHING]: [ORDER_STATUS.DRYING, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.DRYING]: [ORDER_STATUS.IRONING, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.IRONING]: [ORDER_STATUS.PACKING, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PACKING]: [ORDER_STATUS.READY, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.READY]: [ORDER_STATUS.DELIVERED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.DELIVERED]: [ORDER_STATUS.COMPLETED],
  [ORDER_STATUS.COMPLETED]: [],
  [ORDER_STATUS.CANCELLED]: [],
};

const PAYMENT_METHOD = {
  CASH: 'CASH',
  QRIS: 'QRIS',
  EWALLET: 'EWALLET',
};

const PAYMENT_STATUS = {
  UNPAID: 'UNPAID',
  PAID: 'PAID',
  REFUNDED: 'REFUNDED',
};

const SERVICE_TYPE = {
  KILOAN: 'KILOAN',
  SATUAN: 'SATUAN',
  EXPRESS: 'EXPRESS',
};

const ROLE = {
  ADMIN: 'ADMIN',
  STAFF: 'STAFF',
};

const NOTIFICATION_TYPE = {
  STATUS_UPDATE: 'STATUS_UPDATE',
  PROMO: 'PROMO',
  BILLING: 'BILLING',
};

module.exports = {
  ORDER_STATUS,
  ORDER_STATUS_LABEL,
  ORDER_TRANSITIONS,
  PAYMENT_METHOD,
  PAYMENT_STATUS,
  SERVICE_TYPE,
  ROLE,
  NOTIFICATION_TYPE,
};
