const ORDER_STATUS = {
  PENDING: 'PENDING',
  WASHING: 'WASHING',
  DRYING: 'DRYING',
  IRONING: 'IRONING',
  READY: 'READY',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const ORDER_STATUS_LABEL = {
  PENDING: 'Menunggu',
  WASHING: 'Dicuci',
  DRYING: 'Dikeringkan',
  IRONING: 'Disetrika',
  READY: 'Siap Diambil',
  DELIVERED: 'Diantar',
  COMPLETED: 'Selesai',
  CANCELLED: 'Dibatalkan',
};

const ORDER_TRANSITIONS = {
  [ORDER_STATUS.PENDING]: [ORDER_STATUS.WASHING, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.WASHING]: [ORDER_STATUS.DRYING, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.DRYING]: [ORDER_STATUS.IRONING, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.IRONING]: [ORDER_STATUS.READY, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.READY]: [ORDER_STATUS.DELIVERED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.DELIVERED]: [ORDER_STATUS.COMPLETED],
  [ORDER_STATUS.COMPLETED]: [],
  [ORDER_STATUS.CANCELLED]: [],
};

const PAYMENT_METHOD = {
  CASH: 'CASH',
  QRIS: 'QRIS',
  TRANSFER: 'TRANSFER',
  EWALLET: 'EWALLET',
};

const EXPENSE_CATEGORY = {
  BAHAN_BAKU: 'BAHAN_BAKU',
  UTILITAS: 'UTILITAS',
  GAJI: 'GAJI',
  ADMINISTRASI: 'ADMINISTRASI',
  LAINNYA: 'LAINNYA',
};

const EXPENSE_CATEGORY_LABEL = {
  BAHAN_BAKU: 'Bahan Baku & Perlengkapan',
  UTILITAS: 'Utilitas & Operasional',
  GAJI: 'Karyawan & Gaji',
  ADMINISTRASI: 'Administrasi',
  LAINNYA: 'Lainnya',
};

const PAYMENT_STATUS = {
  UNPAID: 'UNPAID',
  PAID: 'PAID',
  REFUNDED: 'REFUNDED',
};

const SERVICE_TYPE = {
  KILOAN: 'KILOAN',
  SATUAN: 'SATUAN',
  EXPRESS: 'EXPRESS',
};

const ROLE = {
  ADMIN: 'ADMIN',
  STAFF: 'STAFF',
};

const NOTIFICATION_TYPE = {
  STATUS_UPDATE: 'STATUS_UPDATE',
  PROMO: 'PROMO',
  BILLING: 'BILLING',
};

module.exports = {
  ORDER_STATUS,
  ORDER_STATUS_LABEL,
  ORDER_TRANSITIONS,
  PAYMENT_METHOD,
  PAYMENT_STATUS,
  SERVICE_TYPE,
  ROLE,
  NOTIFICATION_TYPE,
  EXPENSE_CATEGORY,
  EXPENSE_CATEGORY_LABEL,
};
